/*
 * created : Jun 18, 2011
 * by : Latief
 */

/*
 * JMainFrame.java
 *
 * Created on Jun 18, 2011, 10:24:31 AM
 */
package latief.hotel.swing;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import latief.hotel.controller.HotelController;
import latief.hotel.model.Kamar;
import latief.hotel.model.Tamu;
import org.prambananswing.swing.combobox.BeanComboBoxModel;
import org.prambananswing.swing.table.BeanTableModel;

/**
 *
 * @author Latief
 */
public class JMainFrame extends javax.swing.JFrame {

    /** Creates new form JMainFrame */
    public JMainFrame() {
        initComponents();
        
        jScrollPaneDaftarTamu.getViewport().setOpaque(false);
        jScrollPaneTagihan.getViewport().setOpaque(false);
        
        hotelController = new HotelController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCheckIn = new javax.swing.JPanel();
        jLabelCheckInTitle = new javax.swing.JLabel();
        jLabelCheckInNoIdentitas = new javax.swing.JLabel();
        jLabelCheckInName = new javax.swing.JLabel();
        jLabelCheckInDateIn = new javax.swing.JLabel();
        jLabelCheckInDateOut = new javax.swing.JLabel();
        jLabelCheckInKamar = new javax.swing.JLabel();
        jLabelCheckInTotalCost = new javax.swing.JLabel();
        jTextFieldCheckInNoIdentitas = new javax.swing.JTextField();
        jTextFieldCheckInNama = new javax.swing.JTextField();
        jDateChooserCheckInIn = new com.toedter.calendar.JDateChooser();
        jDateChooserCheckInOut = new com.toedter.calendar.JDateChooser();
        jComboBoxCheckInRoom = new javax.swing.JComboBox();
        jTextFieldCheckInTotalBiaya = new javax.swing.JTextField();
        jLabelCheckInSubmit = new javax.swing.JButton();
        jPanelCheckOut = new javax.swing.JPanel();
        jLabelCheckOutTitle = new javax.swing.JLabel();
        jLabelCheckOutKamar = new javax.swing.JLabel();
        jLabelCheckOutNoIdentitas = new javax.swing.JLabel();
        jLabelCheckOutName = new javax.swing.JLabel();
        jLabelCheckOutDateIn = new javax.swing.JLabel();
        jLabelCheckOutDateOut = new javax.swing.JLabel();
        jLabelCheckOutTotalCost = new javax.swing.JLabel();
        jComboBoxCheckOutRoom = new javax.swing.JComboBox();
        jTextFieldCheckOutNoIdentitas = new javax.swing.JTextField();
        jTextFieldCheckOutNama = new javax.swing.JTextField();
        jDateChooserCheckOutIn = new com.toedter.calendar.JDateChooser();
        jDateChooserCheckOutOut = new com.toedter.calendar.JDateChooser();
        jTextFieldCheckOutTotalBiaya = new javax.swing.JTextField();
        jLabelCheckOutSubmit = new javax.swing.JButton();
        jPanelDaftarTamu = new javax.swing.JPanel();
        jLabelDaftarTamuTitle = new javax.swing.JLabel();
        jScrollPaneDaftarTamu = new javax.swing.JScrollPane();
        jTableDaftarTamu = new org.prambananswing.swing.table.JPTable();
        jPanelTagihan = new javax.swing.JPanel();
        jLabelTagihan = new javax.swing.JLabel();
        jScrollPaneTagihan = new javax.swing.JScrollPane();
        jTableDaftarTagihan = new org.prambananswing.swing.table.JPTable();
        jPanelCariTamu = new javax.swing.JPanel();
        jLabelCariTamu = new javax.swing.JLabel();
        jLabelCariTamuNama = new javax.swing.JLabel();
        jLabelCariTamuMetode = new javax.swing.JLabel();
        jTextFieldCariTamuNama = new javax.swing.JTextField();
        jComboBoxCariTamuMetode = new javax.swing.JComboBox();
        jLabelCariTamuSubmit = new javax.swing.JButton();
        jLabelCariNoIdentitas = new javax.swing.JLabel();
        jLabelCariName = new javax.swing.JLabel();
        jLabelCariDateIn = new javax.swing.JLabel();
        jLabelCariDateOut = new javax.swing.JLabel();
        jLabelCariKamar = new javax.swing.JLabel();
        jLabelCariTotalCost = new javax.swing.JLabel();
        jTextFieldCariNoIdentitas = new javax.swing.JTextField();
        jTextFieldCariNama = new javax.swing.JTextField();
        jDateChooserCariIn = new com.toedter.calendar.JDateChooser();
        jDateChooserCariOut = new com.toedter.calendar.JDateChooser();
        jTextFieldCariKamar = new javax.swing.JTextField();
        jTextFieldCariTotalBiaya = new javax.swing.JTextField();
        jBackground = new org.prambananswing.swing.panel.JPPanel();
        jPanelCard = new org.prambananswing.swing.panel.JPPanel();
        jPanelWelcome = new javax.swing.JPanel();
        jPanelMenu = new org.prambananswing.swing.panel.JPPanel();
        labelCheckIn = new javax.swing.JLabel();
        labelCheckOut = new javax.swing.JLabel();
        labelDaftarTamu = new javax.swing.JLabel();
        labelTagihan = new javax.swing.JLabel();
        labelCari = new javax.swing.JLabel();

        jPanelCheckIn.setOpaque(false);

        jLabelCheckInTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInTitle.setText("Check In");

        jLabelCheckInNoIdentitas.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInNoIdentitas.setText("No Identitas");

        jLabelCheckInName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInName.setText("Nama");

        jLabelCheckInDateIn.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInDateIn.setText("Tanggal Check In");

        jLabelCheckInDateOut.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInDateOut.setText("Tanggal Check Out");

        jLabelCheckInKamar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInKamar.setText("Kamar");

        jLabelCheckInTotalCost.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckInTotalCost.setText("Total Biaya");

        jDateChooserCheckInIn.setOpaque(false);

        jDateChooserCheckInOut.setOpaque(false);

        jComboBoxCheckInRoom.setOpaque(false);
        jComboBoxCheckInRoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCheckInRoomItemStateChanged(evt);
            }
        });

        jTextFieldCheckInTotalBiaya.setEditable(false);

        jLabelCheckInSubmit.setText("check in");
        jLabelCheckInSubmit.setOpaque(false);
        jLabelCheckInSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelCheckInSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCheckInLayout = new javax.swing.GroupLayout(jPanelCheckIn);
        jPanelCheckIn.setLayout(jPanelCheckInLayout);
        jPanelCheckInLayout.setHorizontalGroup(
            jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCheckInTitle)
                    .addGroup(jPanelCheckInLayout.createSequentialGroup()
                        .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCheckInDateIn)
                            .addComponent(jLabelCheckInNoIdentitas)
                            .addComponent(jLabelCheckInName)
                            .addComponent(jLabelCheckInDateOut)
                            .addComponent(jLabelCheckInKamar)
                            .addComponent(jLabelCheckInTotalCost))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCheckInNama, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCheckInNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxCheckInRoom, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooserCheckInOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooserCheckInIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCheckInTotalBiaya, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jLabelCheckInSubmit))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanelCheckInLayout.setVerticalGroup(
            jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCheckInTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckInNoIdentitas)
                    .addComponent(jTextFieldCheckInNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckInName)
                    .addComponent(jTextFieldCheckInNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckInLayout.createSequentialGroup()
                        .addComponent(jDateChooserCheckInIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserCheckInOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckInLayout.createSequentialGroup()
                        .addComponent(jLabelCheckInDateIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCheckInDateOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCheckInRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCheckInKamar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCheckInTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCheckInTotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCheckInSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCheckOut.setOpaque(false);

        jLabelCheckOutTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutTitle.setText("Check Out");

        jLabelCheckOutKamar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutKamar.setText("Kamar");

        jLabelCheckOutNoIdentitas.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutNoIdentitas.setText("No Identitas");

        jLabelCheckOutName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutName.setText("Nama");

        jLabelCheckOutDateIn.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutDateIn.setText("Tanggal Check In");

        jLabelCheckOutDateOut.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutDateOut.setText("Tanggal Check Out");

        jLabelCheckOutTotalCost.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCheckOutTotalCost.setText("Total Biaya");

        jComboBoxCheckOutRoom.setOpaque(false);
        jComboBoxCheckOutRoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCheckOutRoomItemStateChanged(evt);
            }
        });

        jTextFieldCheckOutNoIdentitas.setEditable(false);

        jTextFieldCheckOutNama.setEditable(false);

        jDateChooserCheckOutIn.setEnabled(false);
        jDateChooserCheckOutIn.setOpaque(false);

        jDateChooserCheckOutOut.setEnabled(false);
        jDateChooserCheckOutOut.setOpaque(false);

        jTextFieldCheckOutTotalBiaya.setEditable(false);

        jLabelCheckOutSubmit.setText("check out");
        jLabelCheckOutSubmit.setOpaque(false);
        jLabelCheckOutSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelCheckOutSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCheckOutLayout = new javax.swing.GroupLayout(jPanelCheckOut);
        jPanelCheckOut.setLayout(jPanelCheckOutLayout);
        jPanelCheckOutLayout.setHorizontalGroup(
            jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCheckOutTitle)
                    .addGroup(jPanelCheckOutLayout.createSequentialGroup()
                        .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCheckOutDateIn)
                            .addComponent(jLabelCheckOutNoIdentitas)
                            .addComponent(jLabelCheckOutName)
                            .addComponent(jLabelCheckOutDateOut)
                            .addComponent(jLabelCheckOutKamar)
                            .addComponent(jLabelCheckOutTotalCost))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCheckOutNama, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCheckOutNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooserCheckOutOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooserCheckOutIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCheckOutTotalBiaya, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jComboBoxCheckOutRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCheckOutSubmit))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanelCheckOutLayout.setVerticalGroup(
            jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCheckOutTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckOutKamar)
                    .addComponent(jComboBoxCheckOutRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckOutNoIdentitas)
                    .addComponent(jTextFieldCheckOutNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckOutName)
                    .addComponent(jTextFieldCheckOutNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckOutLayout.createSequentialGroup()
                        .addComponent(jDateChooserCheckOutIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserCheckOutOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckOutLayout.createSequentialGroup()
                        .addComponent(jLabelCheckOutDateIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCheckOutDateOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCheckOutTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCheckOutTotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCheckOutSubmit)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanelDaftarTamu.setOpaque(false);

        jLabelDaftarTamuTitle.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelDaftarTamuTitle.setText("Daftar Tamu");

        jScrollPaneDaftarTamu.setOpaque(false);

        jTableDaftarTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDaftarTamu.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTableDaftarTamu.setOpaque(false);
        jScrollPaneDaftarTamu.setViewportView(jTableDaftarTamu);

        javax.swing.GroupLayout jPanelDaftarTamuLayout = new javax.swing.GroupLayout(jPanelDaftarTamu);
        jPanelDaftarTamu.setLayout(jPanelDaftarTamuLayout);
        jPanelDaftarTamuLayout.setHorizontalGroup(
            jPanelDaftarTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDaftarTamuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDaftarTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDaftarTamu, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jLabelDaftarTamuTitle))
                .addContainerGap())
        );
        jPanelDaftarTamuLayout.setVerticalGroup(
            jPanelDaftarTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDaftarTamuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDaftarTamuTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDaftarTamu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTagihan.setOpaque(false);

        jLabelTagihan.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelTagihan.setText("Tagihan");

        jScrollPaneTagihan.setOpaque(false);

        jTableDaftarTagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDaftarTagihan.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jTableDaftarTagihan.setOpaque(false);
        jScrollPaneTagihan.setViewportView(jTableDaftarTagihan);

        javax.swing.GroupLayout jPanelTagihanLayout = new javax.swing.GroupLayout(jPanelTagihan);
        jPanelTagihan.setLayout(jPanelTagihanLayout);
        jPanelTagihanLayout.setHorizontalGroup(
            jPanelTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTagihanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jLabelTagihan))
                .addContainerGap())
        );
        jPanelTagihanLayout.setVerticalGroup(
            jPanelTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTagihanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTagihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCariTamu.setOpaque(false);

        jLabelCariTamu.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariTamu.setText("Pencarian Tamu");

        jLabelCariTamuNama.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariTamuNama.setText("Nama");

        jLabelCariTamuMetode.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariTamuMetode.setText("Metode");

        jComboBoxCariTamuMetode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sequence", "Binary Iteration", "Binary Recursion" }));
        jComboBoxCariTamuMetode.setOpaque(false);

        jLabelCariTamuSubmit.setText("Cari");
        jLabelCariTamuSubmit.setOpaque(false);
        jLabelCariTamuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelCariTamuSubmitActionPerformed(evt);
            }
        });

        jLabelCariNoIdentitas.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariNoIdentitas.setText("No Identitas");

        jLabelCariName.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariName.setText("Nama");

        jLabelCariDateIn.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariDateIn.setText("Tanggal Check In");

        jLabelCariDateOut.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariDateOut.setText("Tanggal Check Out");

        jLabelCariKamar.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariKamar.setText("Kamar");

        jLabelCariTotalCost.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelCariTotalCost.setText("Total Biaya");

        jTextFieldCariNoIdentitas.setEditable(false);

        jTextFieldCariNama.setEditable(false);

        jDateChooserCariIn.setEnabled(false);
        jDateChooserCariIn.setOpaque(false);

        jDateChooserCariOut.setEnabled(false);
        jDateChooserCariOut.setOpaque(false);

        jTextFieldCariKamar.setEditable(false);

        jTextFieldCariTotalBiaya.setEditable(false);

        javax.swing.GroupLayout jPanelCariTamuLayout = new javax.swing.GroupLayout(jPanelCariTamu);
        jPanelCariTamu.setLayout(jPanelCariTamuLayout);
        jPanelCariTamuLayout.setHorizontalGroup(
            jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCariTamu)
                    .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCariTamuLayout.createSequentialGroup()
                                .addComponent(jLabelCariTamuMetode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxCariTamuMetode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCariTamuLayout.createSequentialGroup()
                                .addComponent(jLabelCariTamuNama)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCariTamuNama, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCariTamuSubmit))
                    .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCariDateIn)
                                            .addComponent(jLabelCariName)
                                            .addComponent(jLabelCariNoIdentitas))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCariNama, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(jDateChooserCariIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCariNoIdentitas)))
                                    .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCariDateOut)
                                            .addComponent(jLabelCariKamar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooserCariOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCariKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCariTotalBiaya))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelCariTotalCost))
                        .addGap(1, 1, 1)))
                .addGap(127, 127, 127))
        );
        jPanelCariTamuLayout.setVerticalGroup(
            jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCariTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCariTamuNama)
                    .addComponent(jTextFieldCariTamuNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCariTamuMetode)
                    .addComponent(jComboBoxCariTamuMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCariTamuSubmit))
                .addGap(18, 18, 18)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCariTamuLayout.createSequentialGroup()
                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCariNoIdentitas)
                            .addComponent(jTextFieldCariNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCariName)
                            .addComponent(jTextFieldCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabelCariDateIn))
                    .addComponent(jDateChooserCariIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserCariOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCariDateOut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCariKamar)
                    .addComponent(jTextFieldCariKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCariTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCariTotalCost)
                    .addComponent(jTextFieldCariTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel");

        jPanelCard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCard.setIcon(null);
        jPanelCard.setOpaque(false);
        jPanelCard.setLayout(new java.awt.CardLayout());

        jPanelWelcome.setOpaque(false);

        javax.swing.GroupLayout jPanelWelcomeLayout = new javax.swing.GroupLayout(jPanelWelcome);
        jPanelWelcome.setLayout(jPanelWelcomeLayout);
        jPanelWelcomeLayout.setHorizontalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanelWelcomeLayout.setVerticalGroup(
            jPanelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jPanelCard.add(jPanelWelcome, "card2");

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setIcon(null);
        jPanelMenu.setOpaque(false);

        labelCheckIn.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        labelCheckIn.setText("Check In");
        labelCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCheckInMouseClicked(evt);
            }
        });

        labelCheckOut.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        labelCheckOut.setText("Check Out");
        labelCheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCheckOutMouseClicked(evt);
            }
        });

        labelDaftarTamu.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        labelDaftarTamu.setText("Daftar Tamu");
        labelDaftarTamu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDaftarTamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDaftarTamuMouseClicked(evt);
            }
        });

        labelTagihan.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        labelTagihan.setText("Tagihan");
        labelTagihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelTagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTagihanMouseClicked(evt);
            }
        });

        labelCari.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        labelCari.setText("Pencarian");
        labelCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCariMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(labelCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(labelDaftarTamu, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(labelTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(labelCari, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCheckOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDaftarTamu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTagihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCari)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jBackgroundLayout = new javax.swing.GroupLayout(jBackground);
        jBackground.setLayout(jBackgroundLayout);
        jBackgroundLayout.setHorizontalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBackgroundLayout.setVerticalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-518)/2, 616, 518);
    }// </editor-fold>//GEN-END:initComponents

    private void labelCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCheckInMouseClicked
        showPanelCheckIn();
    }//GEN-LAST:event_labelCheckInMouseClicked

    private void labelCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCheckOutMouseClicked
        showPanelCheckOut();
    }//GEN-LAST:event_labelCheckOutMouseClicked

    private void labelDaftarTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDaftarTamuMouseClicked
        showPanelDaftarTamu();
    }//GEN-LAST:event_labelDaftarTamuMouseClicked

    private void labelTagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTagihanMouseClicked
        showPanelTagihan();
    }//GEN-LAST:event_labelTagihanMouseClicked

    private void jLabelCheckInSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelCheckInSubmitActionPerformed
        submitCheckIn();
    }//GEN-LAST:event_jLabelCheckInSubmitActionPerformed

    private void jComboBoxCheckInRoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCheckInRoomItemStateChanged
        showCost();
    }//GEN-LAST:event_jComboBoxCheckInRoomItemStateChanged

    private void jComboBoxCheckOutRoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCheckOutRoomItemStateChanged
        showTamuCheckOut();
    }//GEN-LAST:event_jComboBoxCheckOutRoomItemStateChanged

    private void jLabelCheckOutSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelCheckOutSubmitActionPerformed
        submitCheckOut();
    }//GEN-LAST:event_jLabelCheckOutSubmitActionPerformed

    private void jLabelCariTamuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelCariTamuSubmitActionPerformed
        submitCari();
    }//GEN-LAST:event_jLabelCariTamuSubmitActionPerformed

    private void labelCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCariMouseClicked
        showPanelCari();
    }//GEN-LAST:event_labelCariMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.prambananswing.swing.panel.JPPanel jBackground;
    private javax.swing.JComboBox jComboBoxCariTamuMetode;
    private javax.swing.JComboBox jComboBoxCheckInRoom;
    private javax.swing.JComboBox jComboBoxCheckOutRoom;
    private com.toedter.calendar.JDateChooser jDateChooserCariIn;
    private com.toedter.calendar.JDateChooser jDateChooserCariOut;
    private com.toedter.calendar.JDateChooser jDateChooserCheckInIn;
    private com.toedter.calendar.JDateChooser jDateChooserCheckInOut;
    private com.toedter.calendar.JDateChooser jDateChooserCheckOutIn;
    private com.toedter.calendar.JDateChooser jDateChooserCheckOutOut;
    private javax.swing.JLabel jLabelCariDateIn;
    private javax.swing.JLabel jLabelCariDateOut;
    private javax.swing.JLabel jLabelCariKamar;
    private javax.swing.JLabel jLabelCariName;
    private javax.swing.JLabel jLabelCariNoIdentitas;
    private javax.swing.JLabel jLabelCariTamu;
    private javax.swing.JLabel jLabelCariTamuMetode;
    private javax.swing.JLabel jLabelCariTamuNama;
    private javax.swing.JButton jLabelCariTamuSubmit;
    private javax.swing.JLabel jLabelCariTotalCost;
    private javax.swing.JLabel jLabelCheckInDateIn;
    private javax.swing.JLabel jLabelCheckInDateOut;
    private javax.swing.JLabel jLabelCheckInKamar;
    private javax.swing.JLabel jLabelCheckInName;
    private javax.swing.JLabel jLabelCheckInNoIdentitas;
    private javax.swing.JButton jLabelCheckInSubmit;
    private javax.swing.JLabel jLabelCheckInTitle;
    private javax.swing.JLabel jLabelCheckInTotalCost;
    private javax.swing.JLabel jLabelCheckOutDateIn;
    private javax.swing.JLabel jLabelCheckOutDateOut;
    private javax.swing.JLabel jLabelCheckOutKamar;
    private javax.swing.JLabel jLabelCheckOutName;
    private javax.swing.JLabel jLabelCheckOutNoIdentitas;
    private javax.swing.JButton jLabelCheckOutSubmit;
    private javax.swing.JLabel jLabelCheckOutTitle;
    private javax.swing.JLabel jLabelCheckOutTotalCost;
    private javax.swing.JLabel jLabelDaftarTamuTitle;
    private javax.swing.JLabel jLabelTagihan;
    private org.prambananswing.swing.panel.JPPanel jPanelCard;
    private javax.swing.JPanel jPanelCariTamu;
    private javax.swing.JPanel jPanelCheckIn;
    private javax.swing.JPanel jPanelCheckOut;
    private javax.swing.JPanel jPanelDaftarTamu;
    private org.prambananswing.swing.panel.JPPanel jPanelMenu;
    private javax.swing.JPanel jPanelTagihan;
    private javax.swing.JPanel jPanelWelcome;
    private javax.swing.JScrollPane jScrollPaneDaftarTamu;
    private javax.swing.JScrollPane jScrollPaneTagihan;
    private org.prambananswing.swing.table.JPTable jTableDaftarTagihan;
    private org.prambananswing.swing.table.JPTable jTableDaftarTamu;
    private javax.swing.JTextField jTextFieldCariKamar;
    private javax.swing.JTextField jTextFieldCariNama;
    private javax.swing.JTextField jTextFieldCariNoIdentitas;
    private javax.swing.JTextField jTextFieldCariTamuNama;
    private javax.swing.JTextField jTextFieldCariTotalBiaya;
    private javax.swing.JTextField jTextFieldCheckInNama;
    private javax.swing.JTextField jTextFieldCheckInNoIdentitas;
    private javax.swing.JTextField jTextFieldCheckInTotalBiaya;
    private javax.swing.JTextField jTextFieldCheckOutNama;
    private javax.swing.JTextField jTextFieldCheckOutNoIdentitas;
    private javax.swing.JTextField jTextFieldCheckOutTotalBiaya;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelCheckIn;
    private javax.swing.JLabel labelCheckOut;
    private javax.swing.JLabel labelDaftarTamu;
    private javax.swing.JLabel labelTagihan;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Class untuk operasi logic dan perhitungan.
     */
    private HotelController hotelController;
    
    /**
     *
     * Tampilkan AbstractComponentCardLayout di layar
     *
     * @param componentCardLayout AbstractComponentCardLayout yang akan ditampilkan
     */
    private void showCardLayout(JPanel componentCardLayout, String cardName){
        jPanelCard.removeAll();
        jPanelCard.add(componentCardLayout, cardName);
        ((CardLayout)jPanelCard.getLayout()).first(jPanelCard);
    }

    /**
     * Tampilkan PanelCheckIn
     */
    private void showPanelCheckIn(){
        clearInputCheckIn();
        reModelComboBoxKamarCheckIn();
        showCardLayout(jPanelCheckIn, "cardCheckIn");
    }
    
    /**
     * Tampilkan PanelCheckOut
     */
    private void showPanelCheckOut(){
        clearOutputCheckOut();
        reModelComboBoxKamarCheckOut();
        showCardLayout(jPanelCheckOut, "cardCheckOut");
    }
    
    /**
     * Tampilkan PanelDaftarTamu
     */
    private void showPanelDaftarTamu(){
        showDaftarTamu();
        showCardLayout(jPanelDaftarTamu, "cardDaftarTamu");
    }
    
    /**
     * Tampilkan PanelTagihan
     */
    private void showPanelTagihan(){
        showTagihan();
        showCardLayout(jPanelTagihan, "cardTagihan");
    }
    
    /**
     * Tampilkan PanelCari
     */
    private void showPanelCari(){
        //showTagihan();
        showCardLayout(jPanelCariTamu, "cardCari");
    }
    /**
     * Kejadian ketika tombol CheckIn ditekan. Ketika ditekan maka Kamars tertentu
     * akan tercatat telah dipesan oleh Tamu.
     */
    private void submitCheckIn(){
        //Jika tidak ada ruangan yang dipilih, abaikan proses selanjutnya.
        if(jComboBoxCheckInRoom.getSelectedIndex() < 0){
            clearInputCheckIn();
            return;
        }
        
        //Jika tanggal check out lebih awal dari check in, abaikan proses selanjutnya
        if(jDateChooserCheckInIn.getCalendar().getTimeInMillis() > jDateChooserCheckInOut.getCalendar().getTimeInMillis()){
            jTextFieldCheckInTotalBiaya.setText("");
            return;
        }
        
        //Ambil Kamar yang dipilih
        Kamar kamarSelected = hotelController.findKamar(Integer.parseInt((jComboBoxCheckInRoom.getSelectedItem() + "").substring(0, 3)));
        
        //Catat tamunya
        Tamu tamu = new Tamu();
        tamu.setNoIdentitas(jTextFieldCheckInNoIdentitas.getText().trim());
        tamu.setNama(jTextFieldCheckInNama.getText().trim());
        tamu.setCheckIn(jDateChooserCheckInIn.getCalendar());
        tamu.setCheckOut(jDateChooserCheckInOut.getCalendar());
        tamu.setKamar(kamarSelected);
        tamu.setTotalBiaya(hotelController.calculateCost(kamarSelected, tamu.getCheckIn(), tamu.getCheckOut()));
        
        //Tambah ke daftar tamu
        hotelController.addTamu(tamu);
        
        reModelComboBoxKamarCheckIn();
        clearInputCheckIn();
    }
    
    /**
     * Kejadian ketika tombol check out ditekan. Ketika check out maka Kamar 
     * tertentu akan kosong dan Tamu berkurang jumlahnya.
     */
    private void submitCheckOut(){
        //Jika tidak ada kamar yang dipilih, abaikan proses selanjutnya.
        if(jComboBoxCheckOutRoom.getSelectedIndex() < 0){
            clearOutputCheckOut();
            return;
        }
        
        //Ambil kamar mana yang dipilih
        Kamar kamarSelected = hotelController.findKamar(Integer.parseInt((jComboBoxCheckOutRoom.getSelectedItem() + "").substring(0, 3)));
        
        //Hapus Tamu yang check out dari daftar Tamu
        hotelController.removeTamu(kamarSelected);
        
        reModelComboBoxKamarCheckOut();
        clearOutputCheckOut();
    }
    
    /**
     * Kejadian tombol cari ditekan.
     */
    private void submitCari(){
        clearOutputCari();
        
        if(jTextFieldCariTamuNama.getText().trim().isEmpty()){
            return;
        }
        
        String nama = jTextFieldCariTamuNama.getText().trim();
        
        Tamu tamu = hotelController.search(nama, jComboBoxCariTamuMetode.getSelectedIndex());
        
        if(tamu == null){
            JOptionPane.showConfirmDialog(this, "Tamu tidak ditemukan", "Tidak Ditemukan", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        jTextFieldCariNoIdentitas.setText(tamu.getNoIdentitas());
        jTextFieldCariNama.setText(tamu.getNama());
        jDateChooserCariIn.setCalendar(tamu.getCheckIn());
        jDateChooserCariOut.setCalendar(tamu.getCheckOut());
        jTextFieldCariKamar.setText(tamu.getKamar().toString());
        jTextFieldCariTotalBiaya.setText(tamu.getTotalBiaya() + "");
    }
    
    /**
     * Tampilkan Daftar Tamu ke dalam jTableDaftarTamu
     */
    private void showDaftarTamu(){
        String [] columnNames = {"No Identitas", "Nama", "Check In", "Check Out", "Kamar", "Total Biaya"};
        boolean [] columnVisible = {true,true,true,true,true,true};
        setTableModel(jTableDaftarTamu, hotelController.getTamus(), columnNames, columnVisible);
    }
    
    /**
     * Tampilkan Daftar Tagihan ke dalam jTableDaftarTagihan
     */
    private void showTagihan(){
        String [] columnNames = {"No Kamar","Jenis Kamar", "No Identitas", "Nama", "Check In", "Check Out","Total Biaya"};
        boolean [] columnVisible = {true,true,true,true,true,true,true};
        setTableModel(jTableDaftarTagihan, hotelController.getTagihans(), columnNames, columnVisible);
    }
    
    /**
     * Tampilkan Total biaya ketika ada Kamar yang dipilih.
     */
    private void showCost(){
        //Jika ada Kamar/CheckIn/CheckOut yang dipilih, abaikan proses selanjutnya.
        if(jComboBoxCheckInRoom.getSelectedIndex() < 0 
                && jDateChooserCheckInIn.getCalendar() == null
                && jDateChooserCheckInOut.getCalendar() == null){
            jTextFieldCheckInTotalBiaya.setText("");
            return;
        }
        
        //Jika tanggal check out lebih awal dari check in, abaikan proses selanjutnya
        if(jDateChooserCheckInIn.getCalendar().getTimeInMillis() > jDateChooserCheckInOut.getCalendar().getTimeInMillis()){
            jTextFieldCheckInTotalBiaya.setText("");
            return;
        }
        
        //Ambil Kamar yang dipilih
        Kamar kamarSelected = hotelController.findKamar(Integer.parseInt((jComboBoxCheckInRoom.getSelectedItem() + "").substring(0, 3)));
        //Hitung biaya, kemudian tampilkan.
        int cost = hotelController.calculateCost(kamarSelected, jDateChooserCheckInIn.getCalendar(), jDateChooserCheckInOut.getCalendar());
        jTextFieldCheckInTotalBiaya.setText("" + cost);
    }
    
    /**
     * Tampilkan data Tamu yang akan di-check out di PanelCheckOut.
     */
    private void showTamuCheckOut(){
        //Jika tidak ada Kamar yang akan di checkout, abaikan proses selanjutnya.
        if(jComboBoxCheckOutRoom.getSelectedIndex() < 0){
            return;
        }
        
        //Ambil Kamar yang akan di check out.
        Kamar kamarSelected = hotelController.findKamar(Integer.parseInt((jComboBoxCheckOutRoom.getSelectedItem() + "").substring(0, 3)));
        
        //Tampilakn data Tamu yang akan di check out di Component Output PanelCheckOut
        Tamu tamu = hotelController.findTamu(kamarSelected);
        jTextFieldCheckOutNoIdentitas.setText(tamu.getNoIdentitas());
        jTextFieldCheckOutNama.setText(tamu.getNama());
        jDateChooserCheckOutIn.setCalendar(tamu.getCheckIn());
        jDateChooserCheckOutOut.setCalendar(tamu.getCheckOut());
        jTextFieldCheckOutTotalBiaya.setText(tamu.getTotalBiaya() + "");
    }
    
    /**
     * Bersihkan Component input pada PanelCheckIn
     */
    private void clearInputCheckIn(){
        jTextFieldCheckInNoIdentitas.setText("");
        jTextFieldCheckInNama.setText("");
        jDateChooserCheckInIn.setCalendar(null);
        jDateChooserCheckInOut.setCalendar(null);
        jComboBoxCheckInRoom.setSelectedIndex(-1);
        jTextFieldCheckInTotalBiaya.setText("");
    }
    
    /**
     * Bersihkan Component output pada Panel CheckOut
     */
    private void clearOutputCheckOut(){
        jTextFieldCheckOutNoIdentitas.setText("");
        jTextFieldCheckOutNama.setText("");
        jDateChooserCheckOutIn.setCalendar(null);
        jDateChooserCheckOutOut.setCalendar(null);
        jComboBoxCheckOutRoom.setSelectedIndex(-1);
        jTextFieldCheckOutTotalBiaya.setText("");
    }
    
    /**
     * Bersihkan Component input pada PanelCheckIn
     */
    private void clearOutputCari(){
        jTextFieldCariNoIdentitas.setText("");
        jTextFieldCariNama.setText("");
        jDateChooserCariIn.setCalendar(null);
        jDateChooserCariOut.setCalendar(null);
        jTextFieldCariKamar.setText("");
        jTextFieldCariTotalBiaya.setText("");
    }
    
    /**
     * Di modelin ulang untuk jComboBoxCheckInRoom agar menampilkan data kamar yang kosong.
     */
    private void reModelComboBoxKamarCheckIn(){
        setComboBoxModelKamar(jComboBoxCheckInRoom, hotelController.findEmptyKamars());
    }
    
    /**
     * Di modelin ulang untuk jComboBoxCheckOutRoom agar menampilkan data kamar yang isi.
     */
    private void reModelComboBoxKamarCheckOut(){
        setComboBoxModelKamar(jComboBoxCheckOutRoom, hotelController.findFullKamars());
    }
    
    /**
     * Set JComboBox dengan daftar Kamar.
     * @param comboBox
     * @param kamars 
     */
    private void setComboBoxModelKamar(JComboBox comboBox, List<Kamar> kamars){
        boolean [] fieldVisible = {true,false,true};
        BeanComboBoxModel model = new BeanComboBoxModel(kamars, fieldVisible, " - ");
        comboBox.setModel(model);
    }
    
    /**
     * Menampilkan Daftar data ke dalam JTable.
     * @param table
     * @param data
     * @param columnNames
     * @param columnVisible 
     */
    private void setTableModel(JTable table, List data, String [] columnNames, boolean [] columnVisible){
        BeanTableModel model = new BeanTableModel(data, columnNames);
        model.setColumnVisible(columnVisible);
        table.setModel(model);
    }
}
